language: node_js
node_js: stable

git:
  depth: 5
  quiet: true

branches:
  only:
  - hexo

install:
  - npm install
  - npm install hexo-renderer-marked

cache:
  directories:
    - node_modules

script:
  - hexo clean
  - hexo generate

after_success:
  - cd ./public
  - git init
  - git config user.name "${GIT_USER_NAME}"
  - git config user.email "${GIT_USER_EMAIL}"
  - git add .
  - git commit -m "Update Static Site"
  - git push --force --quiet "https://${ACCESS_TOKEN}@${GIT_URL}" ${TARGET_BRANCH}:${TARGET_BRANCH}